#!/bin/zsh
if [ "$1" = "up" ]
then
    (($(amixer sget Master | grep 'Front Left:' | cut -d '[' -f 2 | cut -d '%' -f 1) < 200)) && amixer -q sset Master 10%+
elif [ "$1" = "down" ]
then 
    (($(amixer sget Master | grep 'Front Left:' | cut -d '[' -f 2 | cut -d '%' -f 1) > 0)) && amixer -q sset Master 10%-
elif [ "$1" = "mute" ]
then
    amixer -q sset Master 0%
else
    echo "Not a valid argument. Use 'up', 'down' or 'mute'"
fi
